# Generated by Django 4.2.26 on 2026-05-11 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import marketplace.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('converted', 'Конверсия'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заявка на добавление бизнеса',
                'verbose_name_plural': 'Заявки на добавление бизнеса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (EN)')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='Название (UZ)')),
                ('slug', models.SlugField(unique=True, verbose_name='URL метка')),
                ('icon_class', models.CharField(blank=True, default='bi bi-grid', max_length=80, verbose_name='Bootstrap icon class')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplace.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон салона')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=marketplace.models.salon_logo_upload_to)),
                ('qr_token', models.CharField(blank=True, help_text='Уникальный токен для QR-кода завершения визита. Генерируется автоматически.', max_length=32, unique=True, verbose_name='QR-токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons', to='marketplace.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to=marketplace.models.service_img_upload_to, verbose_name='Изображение услуги')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marketplace.salon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='SalonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=marketplace.models.salon_gallery_upload_to, verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Описание (необяз.)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.salon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Фото салона',
                'verbose_name_plural': 'Фотографии салона',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PCPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (EN)')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='Название (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('price_per_hour', models.DecimalField(decimal_places=2, help_text='Цена за один ПК в час (sum)', max_digits=10, verbose_name='Цена за час')),
                ('icon_class', models.CharField(blank=True, default='bi bi-pc-display', max_length=80, verbose_name='Иконка')),
                ('color', models.CharField(blank=True, default='#00A3AD', help_text='Hex (e.g. #00A3AD)', max_length=20, verbose_name='Цвет')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_plans', to='marketplace.salon', verbose_name='Салон (PC клуб)')),
            ],
            options={
                'verbose_name': 'Тариф PC клуба',
                'verbose_name_plural': 'Тарифы PC клуба',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мастера')),
                ('specialization_ru', models.CharField(blank=True, max_length=100, verbose_name='Специализация (RU)')),
                ('specialization_en', models.CharField(blank=True, max_length=100, verbose_name='Специализация (EN)')),
                ('specialization_uz', models.CharField(blank=True, max_length=100, verbose_name='Специализация (UZ)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=marketplace.models.master_photo_upload_to, verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='marketplace.salon', verbose_name='Салон')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=1, help_text='Количество часов аренды (для PC клубов)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Часы')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Количество ПК для PC-клубов. Для остальных салонов всегда 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ПК')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='marketplace.master', verbose_name='Мастер')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='marketplace.pcplan', verbose_name='Тариф (PC клуб)')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='marketplace.salon', verbose_name='Салон')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.TextField(verbose_name='Full Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('map_link', models.URLField(blank=True, max_length=500, verbose_name='Map Link')),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='marketplace.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='SalonWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Open time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Close time')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='marketplace.salon')),
            ],
            options={
                'verbose_name': 'Salon working hours',
                'verbose_name_plural': 'Salon working hours',
                'ordering': ['weekday'],
                'unique_together': {('salon', 'weekday')},
            },
        ),
    ]
