# Generated by Django 4.2.26 on 2026-05-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_pc_club',
            field=models.BooleanField(default=False, verbose_name='Это ПК клуб?'),
        ),
    ]
