# Generated by Django 4.2.26 on 2026-02-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salonworkinghours',
            options={'ordering': ['weekday'], 'verbose_name': 'Salon working hours', 'verbose_name_plural': 'Salon working hours'},
        ),
        migrations.AlterField(
            model_name='salonworkinghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Close time'),
        ),
        migrations.AlterField(
            model_name='salonworkinghours',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='salonworkinghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Open time'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.TextField(verbose_name='Full Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('map_link', models.URLField(blank=True, max_length=500, verbose_name='Map Link')),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='marketplace.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
