# Generated by Django 4.2.26 on 2025-12-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, default='bi bi-grid', max_length=80, verbose_name='Bootstrap icon class'),
        ),
    ]
