# Generated by Django 4.2.26 on 2026-05-02 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_salonworkinghours_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Количество ПК для PC-клубов. Для остальных салонов всегда 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ПК'),
        ),
    ]
