# Generated by Django 4.2.26 on 2026-05-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_category_is_pc_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='plan',
        ),
        migrations.DeleteModel(
            name='PCPlan',
        ),
    ]
