# Generated by Django 4.2.26 on 2025-12-15 18:11

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_category_icon_category_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.salon_logo_upload_to, verbose_name='Логотип'),
        ),
    ]
