# Generated by Django 4.2.26 on 2025-12-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_salon_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='services/%d.%m.%Y/', verbose_name='Изображение услуги'),
        ),
    ]
