# Generated by Django 4.2.26 on 2026-05-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_appointment_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('converted', 'Конверсия'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заявка на добавление бизнеса',
                'verbose_name_plural': 'Заявки на добавление бизнеса',
                'ordering': ['-created_at'],
            },
        ),
    ]
