# Generated by Django 4.2.26 on 2025-12-23 17:20

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.master_photo_upload_to, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.service_img_upload_to, verbose_name='Изображение услуги'),
        ),
    ]
