# Generated by Django 4.2.26 on 2026-06-13 06:59

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_drop_pcplan_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL логотипа (внешний/демо)'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.salon_logo_upload_to, verbose_name='Логотип'),
        ),
    ]
