# Generated by Django 4.2.26 on 2026-06-13 07:14

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_salon_logo_url_alter_salon_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.salon_cover_upload_to, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='salon',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL обложки (демо/внешний)'),
        ),
        migrations.AddField(
            model_name='salonphoto',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL фото (демо/внешний)'),
        ),
        migrations.AlterField(
            model_name='salonphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.salon_gallery_upload_to, verbose_name='Фото'),
        ),
    ]
