# Generated by Django 4.2.26 on 2025-12-23 17:25

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_master_photo_alter_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.salon_logo_upload_to),
        ),
    ]
