# Generated by Django 4.2.26 on 2025-12-23 17:37

from django.db import migrations, models
import django.db.models.deletion
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_salon_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=marketplace.models.salon_gallery_upload_to, verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Описание (необяз.)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.salon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Фото салона',
                'verbose_name_plural': 'Фотографии салона',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
    ]
