# Generated by Django 4.2.26 on 2026-01-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_salonphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='name_ru',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='name_uz',
        ),
    ]
