# Generated by Django 4.2.26 on 2026-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_rename_name_ru_salon_name_remove_salon_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Название услуги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salon',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название салона'),
        ),
    ]
