# Generated by Django 4.2.26 on 2025-12-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_user_email'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=1, max_length=100, verbose_name='Название (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (UZ)'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Специализация (EN)'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Специализация (RU)'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Специализация (UZ)'),
        ),
        migrations.AddField(
            model_name='salon',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='salon',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='salon',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AddField(
            model_name='salon',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название салона (EN)'),
        ),
        migrations.AddField(
            model_name='salon',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Название салона (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название салона (UZ)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название услуги (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(default=0, max_length=200, verbose_name='Название услуги (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название услуги (UZ)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_profile', to='accounts.profile'),
        ),
    ]
