# Generated by Django 4.2.26 on 2026-01-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
