# Generated by Django 4.2.26 on 2026-01-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_telegram_id_profile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('uz', 'O‘zbek')], default='ru', max_length=2),
        ),
    ]
