# Generated by Django 4.2.26 on 2026-05-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '—'), ('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], default='', max_length=10, verbose_name='Пол'),
        ),
    ]
