# Generated by Django 4.2.26 on 2026-06-13 06:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pc_clubs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0004_drop_pcplan_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=pc_clubs.models.pc_logo_upload_to, verbose_name='Логотип')),
                ('total_pcs', models.PositiveIntegerField(default=20, verbose_name='Всего ПК')),
                ('qr_token', models.CharField(blank=True, max_length=32, unique=True, verbose_name='QR-токен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_clubs', to='marketplace.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'PC Club',
                'verbose_name_plural': 'PC Clubs',
            },
        ),
        migrations.CreateModel(
            name='PCPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (EN)')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='Название (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час (сум)')),
                ('color', models.CharField(default='#00A3AD', max_length=20, verbose_name='Цвет карточки')),
                ('icon_class', models.CharField(default='bi bi-pc-display', max_length=80, verbose_name='Bootstrap иконка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('pc_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='pc_clubs.pcclub', verbose_name='PC Club')),
            ],
            options={
                'verbose_name': 'PC Plan',
                'verbose_name_plural': 'PC Plans',
                'ordering': ['sort_order', 'price_per_hour'],
            },
        ),
        migrations.CreateModel(
            name='PCBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во ПК')),
                ('hours', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Часов')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Конец')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('pc_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pc_clubs.pcclub', verbose_name='PC Club')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_clubs.pcplan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'PC Booking',
                'verbose_name_plural': 'PC Bookings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PCAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_link', models.URLField(blank=True, max_length=500)),
                ('pc_club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='pc_clubs.pcclub')),
            ],
            options={
                'verbose_name': 'PC Club Address',
            },
        ),
        migrations.CreateModel(
            name='PCWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('is_closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('pc_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='pc_clubs.pcclub')),
            ],
            options={
                'verbose_name': 'PC Club Working Hours',
                'ordering': ['weekday'],
                'unique_together': {('pc_club', 'weekday')},
            },
        ),
    ]
