# Generated by Django 4.2.26 on 2026-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcclub',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL логотипа (демо/внешний)'),
        ),
    ]
