# Generated by Django 4.2.26 on 2026-06-13 07:14

from django.db import migrations, models
import django.db.models.deletion
import pc_clubs.models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_clubs', '0002_pcclub_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcclub',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=pc_clubs.models.pc_cover_upload_to, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='pcclub',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL обложки (демо/внешний)'),
        ),
        migrations.CreateModel(
            name='PCPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=pc_clubs.models.pc_photo_upload_to, verbose_name='Фото')),
                ('photo_url', models.URLField(blank=True, max_length=500, verbose_name='URL фото (демо/внешний)')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pc_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pc_clubs.pcclub', verbose_name='PC Club')),
            ],
            options={
                'verbose_name': 'PC Club Photo',
                'verbose_name_plural': 'PC Club Photos',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
    ]
